version: '3'

services:
  app:
    user: $uid:$gid
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    command: >
      sh -c 'python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - '3309:3306'
    environment:
       MYSQL_DATABASE: 'app_db'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']